### ISSUE TITLE
Wrong OID in the schema when adding attribute

### ISSUE THREAD

**Issue by brice-nandi** [GlobalSign/PKI.js#36]
Hello,

I'm currently trying to send a csr to a Microsoft PKI.
For some reason when I set the attribute this way: 

pkcs10_simpl.attributes.push(new org.pkijs.simpl.ATTRIBUTE({type: "1.3.6.1.4.1.311.13.2.1", values: [new org.pkijs.asn1.UNIVERSALSTRING({ value: "CertificateTemplate" }), new org.pkijs.asn1.UNIVERSALSTRING({ value: "AL_WIFI_Users_NotWindows" })]}));

when I run the code in debug mode the schema contains this list of SID value block:
43,6,1,4,1,311,13,2,1

Is this normal?

**Comment by YuryStrozhevsky** [comment]
The PKIjs made the way when you should not borther about internal coding. Yes, SID array is correct. If you would like to know more about OID encoding and ASN.1 feel free to read [my article](http://www.strozhevsky.com/free_docs/asn1_in_simple_words.pdf).

**Comment by brice-nandi** [comment]
Hello,

Sorry for my mistake.
As I said, I'm fairly new to these things.

I'm currently using PKI.js (for a customer) to enroll Google Chromebook users in a Microsoft PKI using MS-XCEP/MS-WSTEP.
And in order to do that I need to generate a CSR from scratch.
So far so good..
But then I need to add the attribute "CertificateTemplate" attribute and that's where I'm failing..
I always get the message "The request (CSR) does not contain a certificate template extension or the CertificateTemplate request attribute".

Looking at Microsoft documentation, attribute architecture should look like this:
//beginning
30 42				; SEQUENCE (42 Bytes)
|  06 0a				; OBJECT_ID (a Bytes)
|  |  2b 06 01 04 01 82 37 0d  02 01
|  |     ; 1.3.6.1.4.1.311.13.2.1 Enrollment Name Value Pair
|  31 34				; SET (34 Bytes)
|     30 32			; SEQUENCE (32 Bytes)
|        1e 26			; UNICODE_STRING (26 Bytes)
|        |  00 43 00 65 00 72 00 74  00 69 00 66 00 69 00 63  ; .C.e.r.t.i.f.i.c
|        |  00 61 00 74 00 65 00 54  00 65 00 6d 00 70 00 6c  ; .a.t.e.T.e.m.p.l
|        |  00 61 00 74 00 65                                 ; .a.t.e
|        |     ; "CertificateTemplate"
|        1e 08			; UNICODE_STRING (8 Bytes)
|           00 55 00 73 00 65 00 72                           ; .U.s.e.r
|              ; "User"

//end

Have you ever encountered such an issue?
And if not, do you have any idea on how to proceed?

Thank you,

**Comment by YuryStrozhevsky** [comment]
My time is my money. If you would like to hire me then I can think about it but now I am busy at least for nearest two months.

**Comment by brice-nandi** [comment]
I understand that. :)

**Comment by brice-nandi** [comment]
Do you at least have an example of how to add an attribute to a csr?
because there is no example of that.

**Comment by YuryStrozhevsky** [comment]
I do not know what is it - "attribute in CSR".

**Comment by brice-nandi** [comment]
I meant adding attributes in a pkcs10 certificate signing request..

**Comment by rmhrisk** [comment]
Please create a CSR with certreq.exe that looks like you want and paste it here.

**Comment by brice-nandi** [comment]
Hello,

Here is the request and the inf file that I used to generate it.

Brice Nandi
*Deployment Engineer @ *
* revevol*
Revevol France SAS
mobile: +33 6.16.65.09.01

2015-05-08 1:23 GMT+02:00 Ryan Hurst <notifications@github.com>:

**Comment by brice-nandi** [comment]
My bad, it does not send attachment..

Here it is:

-----BEGIN NEW CERTIFICATE REQUEST-----
MIIEmzCCA4MCAQAwQjEeMBwGA1UEAxMVc29tZXRoaW5nLmV4YW1wbGUuY29tMRMw
EQYDVQQKEwpFeGFtcGxlIENvMQswCQYDVQQGEwJVUzCCASIwDQYJKoZIhvcNAQEB
BQADggEPADCCAQoCggEBAMmqT+mGH3W+MP4DHmCWnfgflbU/5hRBARrLFxXQxdcy
i3CYJSgZ2tGE50fZkSp/TMNAgCbe6t2ZzsFg9OlRWn2KIHepzqXdNbgVM8sgd0gh
ImDZX8cSnKrxg2FySkxz2Xoso5mdsX22/os0nlmVYrFCFXrW8AQWbg7bF4stnyDk
Vwx4ruZCqznN/kr3fBxwiw0hGjE1qScRc4eZyAmXk4MWhw6KQHQR4fEwBzcB8Q9j
8+e0UUMCLHGEQbw7AqlYwcRVdEWzm3ypsVf8Y7PBU+NYQA7LDRbaDfyBhdkhHmJc
1SU44+4bLaUvymGb81dVAW13ChbfuPblKxKuXLpM7HUCAwEAAaCCAhIwGgYKKwYB
BAGCNw0CAzEMFgo1LjIuMzc5MC4yMEIGCSsGAQQBgjcVFDE1MDMCAQEMDmRjLnJl
dmV2b2wuY29tDBVSRVZFVk9MXEFkbWluaXN0cmF0b3IMB2NlcnRyZXEwga8GCSqG
SIb3DQEJDjGBoTCBnjAdBgNVHQ4EFgQUIAx/Rb+mElqephfawdPD2pE8/ZEwHAYJ
KwYBBAGCNxUKBA8wDTALBgkrBgEEAYI3FRMwPQYJKwYBBAGCNxUHBDAwLgYmKwYB
BAGCNxUIhcOPQYX58myCgYc/hae7Bob1D4EUhJKzU4WK4l8CAWUCAQAwEwYDVR0l
BAwwCgYIKwYBBQUHAwEwCwYDVR0PBAQDAgWgMIH9BgorBgEEAYI3DQICMYHuMIHr
AgEBHloATQBpAGMAcgBvAHMAbwBmAHQAIABSAFMAQQAgAFMAQwBoAGEAbgBuAGUA
bAAgAEMAcgB5AHAAdABvAGcAcgBhAHAAaABpAGMAIABQAHIAbwB2AGkAZABlAHID
gYkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADANBgkq
hkiG9w0BAQUFAAOCAQEAuKPwAqKfftDCRQRoM95FBvHtKgGBj1PXvyomjIwE5TqU
szOMV/ASJN174/nGc+myvO5Yb0T5QfdjTVUSjjHbxhQqR8quSvUh17+kRAFqB1X1
0ja5PQtTsNyPnyulW1DHyzikRVkEcCR9LI/PGD4+bBSCsJfEP5NIkuRy3W7ClQQ3
ctgbgnTgHFLFGrkU9/uQVVsWAz3KBqBva3/SDSOeWXkBL9tb5qDTutT8/BgywjGa
h5phv4JjI92cSVxtXcptS1HH8pUcfvEBvgtOvmjETn0MgdSfV1xfWKj0Xm7JomXY
BnQQFahJyugd/KoD5OI1bRCG36XBNRbw/zCNXeOWmg==
-----END NEW CERTIFICATE REQUEST-----



INF file:

;----------------- request.inf -----------------

[Version]
Signature="$Windows NT$"

[NewRequest]
;Change to your,country code, company name and common name
Subject = "C=US, O=Example Co, CN=something.example.com"

KeySpec = 1
KeyLength = 2048
Exportable = TRUE
MachineKeySet = TRUE
SMIME = False
PrivateKeyArchive = FALSE
UserProtected = FALSE
UseExistingKeySet = FALSE
ProviderName = "Microsoft RSA SChannel Cryptographic Provider"
ProviderType = 12
RequestType = PKCS10
KeyUsage = 0xa0

[EnhancedKeyUsageExtension]
OID=1.3.6.1.5.5.7.3.1 ; this is for Server Authentication / Token Signing

[RequestAttributes]
CertificateTemplate = AL_WIFI_Users_NotWindows ;
;-----------------------------------------------

Brice Nandi
*Deployment Engineer @ *
* revevol*
Revevol France SAS
mobile: +33 6.16.65.09.01

2015-05-08 14:43 GMT+02:00 Brice Nandi <brice.nandi@revevol.eu>:

**Comment by YuryStrozhevsky** [comment]
This is an invalid encoded request.

**Comment by brice-nandi** [comment]
Hello,

What do you mean by "invalid"?
Certreq did all the work..

**Comment by rmhrisk** [comment]
OK so I am not sure which part of the P10 Yury is saying is Invalid but he is seldom wrong on such things, with that said it its what certreq produces valid or not clients need to support it.

First lets look at your P10 in a pretty print:

http://lapo.it/asn1js/#3082049B308203830201003042311E301C06035504031315736F6D657468696E672E6578616D706C652E636F6D31133011060355040A130A4578616D706C6520436F310B300906035504061302555330820122300D06092A864886F70D01010105000382010F003082010A0282010100C9AA4FE9861F75BE30FE031E60969DF81F95B53FE61441011ACB1715D0C5D7328B7098252819DAD184E747D9912A7F4CC3408026DEEADD99CEC160F4E9515A7D8A2077A9CEA5DD35B81533CB207748212260D95FC7129CAAF18361724A4C73D97A2CA3999DB17DB6FE8B349E599562B142157AD6F004166E0EDB178B2D9F20E4570C78AEE642AB39CDFE4AF77C1C708B0D211A3135A92711738799C80997938316870E8A407411E1F130073701F10F63F3E7B45143022C718441BC3B02A958C1C4557445B39B7CA9B157FC63B3C153E358400ECB0D16DA0DFC8185D9211E625CD52538E3EE1B2DA52FCA619BF35755016D770A16DFB8F6E52B12AE5CBA4CEC750203010001A0820212301A060A2B0601040182370D0203310C160A352E322E333739302E32304206092B0601040182371514313530330201010C0E64632E72657665766F6C2E636F6D0C1552455645564F4C5C41646D696E6973747261746F720C07636572747265713081AF06092A864886F70D01090E3181A130819E301D0603551D0E04160414200C7F45BFA6125A9EA617DAC1D3C3DA913CFD91301C06092B060104018237150A040F300D300B06092B0601040182371513303D06092B06010401823715070430302E06262B060104018237150885C38F4185F9F26C8281873F85A7BB0686F50F81148492B353858AE25F02016502010030130603551D25040C300A06082B06010505070301300B0603551D0F0404030205A03081FD060A2B0601040182370D02023181EE3081EB0201011E5A004D006900630072006F0073006F00660074002000520053004100200053004300680061006E006E0065006C002000430072007900700074006F0067007200610070006800690063002000500072006F007600690064006500720381890000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000300D06092A864886F70D01010505000382010100B8A3F002A29F7ED0C245046833DE4506F1ED2A01818F53D7BF2A268C8C04E53A94B3338C57F01224DD7BE3F9C673E9B2BCEE586F44F941F7634D55128E31DBC6142A47CAAE4AF521D7BFA444016A0755F5D236B93D0B53B0DC8F9F2BA55B50C7CB38A445590470247D2C8FCF183E3E6C1482B097C43F934892E472DD6EC295043772D81B8274E01C52C51AB914F7FB90555B16033DCA06A06F6B7FD20D239E5979012FDB5BE6A0D3BAD4FCFC1832C2319A879A61BF826323DD9C495C6D5DCA6D4B51C7F2951C7EF101BE0B4EBE68C44E7D0C81D49F575C5F58A8F45E6EC9A265D806741015A849CAE81DFCAA03E4E2356D1086DFA5C13516F0FF308D5DE3969A

For your project its important to understand that there are several "versions" of the certificate template extension. The first version used plain strings to communicate what type of certificate to request. The later version (v2) supported versions and used unique IDs to name the templates. If your woking with WSTEP clients you can just do the more complicated one as you wont have interoperability issues since those clients that support WSTEP* will be happy with the newer version.

Looking at your P10 the v2 template is the one numbered "1.3.6.1.4.1.311.21.7" and looks like this:

OBJECT IDENTIFIER1.3.6.1.4.1.311.21.7
OCTET STRING(1 elem)
SEQUENCE(3 elem)
OBJECT IDENTIFIER1.3.6.1.4.1.311.21.8.11585473.12482924.4211647.11132294.113295.148.8690131.10662…
INTEGER101
INTEGER0

You will notice it is contained within a PKCS#9 extension request (1.2.840.113549.1.9.14) which itself is a SET (https://tools.ietf.org/html/rfc2986).

As you have found we do not yet provide an example of how to add request attributes,

**Comment by brice-nandi** [comment]
Hello Ryan,

Thank you for all the information, I'll try to work from that.
And will provide you with the example when (if  :) ) I get it to work.
Thanks again. :)

ps: Just so you know, the fact that pki.js uses Webcrypto standards, makes it easier to integrate with Google "chrome.enterprise.platformKeys" api which makes it (to my opinion) the best alternative right now.
