### ISSUE TITLE
describe asn1js and node.extend dependencies in package.json

### ISSUE THREAD

**Issue by kjur** [GlobalSign/PKI.js#62]
Hi Yuri. Could you add "asn1js" and "node.extend" to "dependencies" seciton in "package.json" for Node.js? It may help easy installation.

**Comment by YuryStrozhevsky** [comment]
In fact I can do this, but it would be useless - currently user will need to merge PKIjs and ASN1js anyway. And for Node.js projects would be easier to have "var asnjs = require("asn1js")" instead of "var asn1js = require("pkijs/node_modules/asn1js")".
Easiest way now is to add dependencies to "end-user" Node.js project and then merge it as shown in README or in [this issue](https://github.com/GlobalSign/PKI.js/issues/49).

**Comment by kjur** [comment]
Thank you for your explanation. I understood.
